FROM ghcr.io/n8n-io/n8n:latest

# Force IPv4 pooling routing to bypass Render's ENETUNREACH block
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=aws-1-ap-south-1.pooler.supabase.com
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=postgres
ENV DB_POSTGRESDB_USER=postgres.rizesvvqlczqbfqhqnxc
ENV DB_POSTGRESDB_PASSWORD=bn_NP6?wknMiJn*
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false

# Keep-alive settings
ENV DB_POSTGRESDB_TIMEOUT=90000
ENV DB_POSTGRESDB_CONNECTION_TIMEOUT=90000
